<?php

namespace Database\Seeders;

use App\Models\ReportFinance;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ReportFinanceSeeder extends Seeder
{
    public function run()
    {
        $users = User::where('role', 'operator')->inRandomOrder()->first();
        
        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 149000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Simpang Pematang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-12',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-15',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 83500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Batin - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 149000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Simpang Pematang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-03',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Menggala',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-05',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-09',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 63,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-10',
            'date_recorded' => '2023-10-01',
            'fuel' => 14.7,
            'fuel_cost' => 100000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 200004 EV 139425 Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-17',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 149000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Simpang Pematang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 140,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 29.41,
            'fuel_cost' => 200000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 201386 EV 139462 Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 155000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter Oli New Pajero G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 420000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter Solar Innova Astra',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 346000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter Udara New Triton',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 315000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter AC Pajero G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 60000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Cliner Injector 250 ml',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 50000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ganti Oli Mesin & Filter Oli',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 275000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Jasa Tune Up & Membersihkan EGR',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 550000,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Service Intake',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8246OA',
            'date_of_application' => '2023-10-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-09-04',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 1531532,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ban Luar GT Savero M/T 245/75/16',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-09-06',
            'date_recorded' => '2023-10-01',
            'fuel' => 54.42,
            'fuel_cost' => 370056,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 262521 EV 139407 by Maman',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-10-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-10-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8145DY',
            'date_of_application' => '2023-10-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 53500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Kotabaru - Sidomulyo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 53500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Sidomulyo - Kotabaru',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-10-14',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 106000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Kotabaru - Bakauheni Selatan',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-10-14',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 106000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Bakauheni Selatan - Kotabaru',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-09-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 1567568,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ban Luar BS Ecopia EP150 185/70/14',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-09-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 55855,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Balancing Velg',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1606DC',
            'date_of_application' => '2023-09-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 137838,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Spooring',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-09-04',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 2522522,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ban Luar GT Savero A/T Plus 245/75/16',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-10',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-10',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-18',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Menggala',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Menggala - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 39000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Menggala',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8493DG',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-12',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 46000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Gunung Sugih',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-12',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 46000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Sugih - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-02',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 46000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Gunung Sugih',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-02',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 68500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Sugih - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-09-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 51.42,
            'fuel_cost' => 350000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 236484 EV 139407 by Maman',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-09-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 51.47,
            'fuel_cost' => 350000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 237092 EV 139407 by Maman',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-09-28',
            'date_recorded' => '2023-10-01',
            'fuel' => 29.41,
            'fuel_cost' => 200000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 237709 EV 139407 by Maman',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 155000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter Oil New Pajero G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 420000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter Solar New Triton G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 315000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Filter AC Pajero G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 346000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Elemen Air Cleaner Strada',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 60000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Cliner Injektor 250 ml',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 50000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ganti Oli Mesin & Filter Oli',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 275000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Jasa Tune Up & Membersihkan EGR',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 550000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Jasa Bongkar Pasang in Take Manifold',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 127,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 20.00,
            'fuel_cost' => 180000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 239887 EV 139490 by Simon',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 127,
            'vehicle_id' => 'BE8414DA',
            'date_of_application' => '2023-10-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 66.02,
            'fuel_cost' => 448936,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 240163 EV 139490 by Simon',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 33,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-04',
            'date_recorded' => '2023-10-01',
            'fuel' => 29.41,
            'fuel_cost' => 200000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota (by Arnold-PTB)',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 83500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Gunung Batin',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 67000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Batin - Tegineneng',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-17',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-17',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 380000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Cliper Kit Strada G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 700000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Piston Cakram Strada Kb7 G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 830000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Kanpas Rem Depan All New Triton G',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 70000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Minyak Rem Preston (Netral)',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 250000,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Jasa Service Rem 4 Roda',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-12',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-12',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-18',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8431OB',
            'date_of_application' => '2023-10-18',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-09-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-09-22',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Panaragan - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-09-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 113000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Tegineneng Barat - Way Kenanga',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-10-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 83500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Gunung Batin',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-10-13',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 83500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Batin - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8751DA',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tp; Natar - Menggala',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-15',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 43000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Tegineneng Barat - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-15',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 83500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Batin - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-04',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 1463964,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ban Luar GT Savero M/T 245/75/16',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-10-14',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 52500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Sidomulyo - Bakauheni',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-10-14',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 94000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Bakauheni - Kotabaru',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-22',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 1531532,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Ban Luar Savero M/T 245/75/16',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-22',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 137838,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Spooring',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-09-22',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 91891,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Balancing Velg',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-09-17',
            'date_recorded' => '2023-10-01',
            'fuel' => 51.5,
            'fuel_cost' => 350000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 263067 EV 139437 by Aldo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-09-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 58.8,
            'fuel_cost' => 400000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 263457 EV 139437 by Aldo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-01',
            'date_recorded' => '2023-10-01',
            'fuel' => 51.5,
            'fuel_cost' => 350000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 263932 EV 139437 by Aldo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-06',
            'date_recorded' => '2023-10-01',
            'fuel' => 51.5,
            'fuel_cost' => 350000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 264232 EV 139437 by Aldo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-18',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Menggala',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-22',
            'date_recorded' => '2023-10-01',
            'fuel' => 44.1,
            'fuel_cost' => 300000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 265222 EV 139470 by Aldo',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 98500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Menggala - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 43000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Tegineneng Barat - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 15000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Way Kenanga - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 15000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Way Kenanga',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 46000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Gunung Sugih',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-27',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 31000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Gunung Sugih - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 148,
            'vehicle_id' => 'BE8977DH',
            'date_of_application' => '2023-10-23',
            'date_recorded' => '2023-10-01',
            'fuel' => 5.69,
            'fuel_cost' => 100000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 266075 EV 139488 by Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-09-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Lambu Kibang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-09-30',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 114500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Lambu Kibang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-09-29',
            'date_recorded' => '2023-10-01',
            'fuel' => 14.71,
            'fuel_cost' => 100000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 200681 EV 139396 by Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-09-30',
            'date_recorded' => '2023-10-01',
            'fuel' => 14.71,
            'fuel_cost' => 100000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 201008 EV 139396 by Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-09-30',
            'date_recorded' => '2023-10-01',
            'fuel' => 17.25,
            'fuel_cost' => 100000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 201114 EV 139396 by Wahyu',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-11',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-19',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-24',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 149000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Simpang Pematang',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 149000,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Simpang Pematang - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Natar - Terbanggi Besar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8260DL',
            'date_of_application' => '2023-10-26',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 59500,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Tol Terbanggi Besar - Natar',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1664DB',
            'date_of_application' => '2023-10-17',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 34544,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Yuasa Acou Zuur SPGR 1260, 1 ltr',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE1664DB',
            'date_of_application' => '2023-10-02',
            'date_recorded' => '2023-10-01',
            'fuel' => 0.00,
            'fuel_cost' => 0,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 802000,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Yuasa NS 60',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 128,
            'vehicle_id' => 'BE8183OB',
            'date_of_application' => '2023-10-25',
            'date_recorded' => '2023-10-01',
            'fuel' => 15.00,
            'fuel_cost' => 135000,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 156416 EV 139493 by Riyan',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => 128,
            'vehicle_id' => 'BE8183OB',
            'date_of_application' => '2023-10-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 59.14,
            'fuel_cost' => 402152,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 156416 EV 139493 by Riyan',
        ]);

        ReportFinance::create([
            'users_id' => $users->id,
            'report_id' => null,
            'vehicle_id' => 'BE8918OB',
            'date_of_application' => '2023-10-21',
            'date_recorded' => '2023-10-01',
            'fuel' => 59.14,
            'fuel_cost' => 402152,
            'stnk_cost' => 0,
            'kir_cost' => 0,
            'repair_cost' => 0,
            'maintenance_cost' => 0,
            'carwash_cost' => 0,
            'toll_cost' => 0,
            'parking_cost' => 0,
            'other_cost' => 0,
            'remark' => 'Solar Luar Kota KM 156693 EV 139493 by Riyan',
        ]);
    }
}
